#auto: true
destination: _site
permalink: /:categories/:title
#url: http://bcman.nwdc.org.uk
#assets_url: http://assets-bcman.nwdc.org.uk
url: /
assets_url: /
s_email: bcman@nwdc.org.uk
s_sponsors: false
exclude: ['rakefile', 'README']